version: "3.9"

services:
  api:
    command: uvicorn stie.api.app:create_app --host 0.0.0.0 --port 8000 --factory --reload
    volumes:
      - ./src:/app/src
    environment:
      - APP_DEBUG=true
      - LOG_LEVEL=DEBUG

  postgres:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  qdrant:
    ports:
      - "6333:6333"

  ollama:
    ports:
      - "11434:11434"
