apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stie-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - stie.quantumworld-dpdns.io
      secretName: stie-tls
  rules:
    - host: stie.quantumworld-dpdns.io
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: stie-api
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stie-api
                port:
                  number: 80
